import {
  Archive,
  AlertCircle,
  ArrowRight,
  BookOpenCheck,
  BookOpen,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Download,
  Edit,
  Eye,
  EyeOff,
  File,
  FileDown,
  FileText,
  Folder,
  FolderOpen,
  History,
  Info,
  ListChecks,
  Loader2,
  Lock,
  LogOut,
  MoreHorizontal,
  Moon,
  Paperclip,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Target,
  TriangleAlert,
  Upload,
  Users,
  X,
  Zap,
} from "lucide-react";

export const icons = {
  archive: Archive,
  alertCircle: AlertCircle,
  arrowRight: ArrowRight,
  book: BookOpen,
  classroom: BookOpenCheck,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  download: Download,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  fileDown: FileDown,
  fileText: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  history: History,
  info: Info,
  listChecks: ListChecks,
  loader: Loader2,
  lock: Lock,
  logout: LogOut,
  moreHorizontal: MoreHorizontal,
  moon: Moon,
  paperclip: Paperclip,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  sparkle: Sparkles,
  star: Star,
  sun: Sun,
  target: Target,
  triangleAlert: TriangleAlert,
  upload: Upload,
  users: Users,
  x: X,
  zap: Zap,
};

export type IconName = keyof typeof icons;

export function AppIcon({ name, className }: { name: IconName; className?: string }) {
  const Icon = icons[name];
  return <Icon className={className ?? "ico"} aria-hidden="true" />;
}
